version: '3'
services:
  express:
    build:
      context: .
      dockerfile: express_docker/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - my-network

networks:
  my-network:
