version: '3'
services:
  express:
    build:
      context: .
      dockerfile: express_docker/Dockerfile
    ports:
      - 3001:3001
  flask:
    build:
      context: .
      dockerfile: flask_docker/Dockerfile
    ports:
      - 5000:5000
