version: '3'
services:
  express:
    build:
      context: .
      dockerfile: express_docker/Dockerfile
    command: sh -c "dockerize -wait tcp://mongodb:27017 -timeout 60s && node app.js"
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    networks:
      - my-network
  flask:
    build:
      context: .
      dockerfile: flask_docker/Dockerfile
    ports:
      - 5000:5000
    networks:
      - my-network
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
